version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: anyhow
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: clap
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: flate2
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: serde
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: thiserror
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: tokio
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: '*'
    update-types:
    - version-update:semver-patch
  labels:
  - dependencies
